spring:
  twelvedata:
    api-key: 7a79c306727443819a002da0398f5ce7
    api-url: https://api.twelvedata.com
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
    baseline-on-migrate: true
    url: jdbc:mysql://localhost:3306/banking
    user: user
    password: 12345
logging:
  level:
    com.bankingsystem.app.services.impl: DEBUG  # Включить логи для вашего класса
    org.springframework.web.client.RestTemplate: DEBUG  # Логировать HTTP-запросы