spring:
  datasource:
    url: jdbc:mysql://mysql:3306/banking?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none #?????????? ???????????? ?????? hibernate, ?????????? Flyway
    show-sql: true #??????????? ????? sql ????????
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true #???? ???? ?????? ??????????, Flyway ?????? ? ???????? ?????????
    url: jdbc:mysql://mysql:3306/banking?useSSL=false&allowPublicKeyRetrieval=true
    user: user
    password: 12345