spring:
  twelvedata:
    api-key: 7a79c306727443819a002da0398f5ce7
    api-url: https://localhost:8089
  datasource:
    url: jdbc:mysql://localhost:3306/testdb
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
    baseline-on-migrate: true
