spring:
  twelvedata.api-key: f16e683590f6486f9aaf9fee18cd4c51
  twelvedata.api.url: https://api.twelvedata.com
  datasource:
    url: jdbc:mysql://localhost:3306/banking
    username: user
    password: 12345
  jpa:
    hibernate:
      ddl-auto: none #?????????? ???????????? ?????? hibernate, ?????????? Flyway
    show-sql: true #??????????? ????? sql ????????
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-migration-naming: true
    baseline-on-migrate: true #???? ???? ?????? ??????????, Flyway ?????? ? ???????? ?????????
    url: jdbc:mysql://localhost:3306/banking
    user: user
    password: 12345
